### ISSUE TITLE
Crop-tool is visual not correct

### ISSUE THREAD

**Issue by jorismeuleman** [doakey3/VSE_Transform_Tools#12]
I like VSE Transform Tools: it makes Blender a usefull video-editor. I have a visual problem with Crop. My videofragment is 3840x2160x25fps and renderoutput is 1920x1080x25fps and you cannot drag the handles to the edges. See printscreen: this is the maximun cropbox.
![VSE Transform Tools - crop-bug](https://user-images.githubusercontent.com/59956404/72514909-5225c400-384f-11ea-89fb-30fabb87cae8.png)

**Comment by doakey3** [comment]
I have been away for a while. I tried to reproduce this issue just now, but was unable. Are you still having this issue?

**Comment by jorismeuleman** [comment]
I don't know what went wrong the moment I posted the bug, but in the meanwhile I used VSE_Transform_Tools to create new movies without any problems.
Thanks for your work in VSE_Transform_Tools. I love it! and use it a lot.
