### ISSUE TITLE
Using a proxy resolution breaks crop in 2.82+

### ISSUE THREAD

**Issue by tin2tin** [doakey3/VSE_Transform_Tools#14]
The crop function works correctly when no proxy resolution is used but breaks when Proxy Resolution is used(on Movie strips, but Color strips still works):
![Crop_proxy_bug](https://user-images.githubusercontent.com/1322593/80674159-5ea5f380-8ab1-11ea-87bd-4c54971aa13a.gif)

On a different note, I've made a fork and implemented toolbar buttons for the main Transform Tools operators: https://github.com/tin2tin/VSE_Transform_Tools When it is finished, I'll send you a patch:
![Transform_toolbar](https://user-images.githubusercontent.com/1322593/80674347-ec81de80-8ab1-11ea-834d-6262018faf8c.gif)

The VSE maintainer expressed interest in having the main Transform Tools included in Blender as either build-in python operators or as an add-on. 
 
Discussion on the toolbar work can be found here: https://blender.chat/channel/vse

**Comment by josselex** [comment]
This seems to be related to
https://developer.blender.org/T51828

**Comment by familyfriendlymikey** [comment]
Seems it was inadvertently fixed by
https://developer.blender.org/T78579

Cropping with proxies works for me in 2.9.
