### ISSUE TITLE
Add-on does not show up in Add-on list in the user preferences 

### ISSUE THREAD

**Issue by Dvavid** [doakey3/VSE_Transform_Tools#2]
Hey -
I just tried to install the Add-on but after loading the .zip, it does not show up in the list.
The files are copied just fine in the .config/blender/2.79/scripts/addons directory, but nothing shows up.
Tested on 2.79 and 2.8. A friend on discord could replicate the issue.

**Comment by doakey3** [comment]
You are right. Give half an hour an I'll have this fixed.

**Comment by Dvavid** [comment]
thank you a lot for the fast fix! I downloaded and it works now. Awesome Add-on!

**Comment by doakey3** [comment]
Oh hold on, still testing. Give me a few more minutes and it will be perfect.

**Comment by doakey3** [comment]
Things seem to be working good now. Thanks so much for reporting an issue. Sometimes things seem to be working fine when they aren't.

**Comment by Dvavid** [comment]
Awesome - thank you very much for your effort! <3

https://imgur.com/q0hOizh
