### ISSUE TITLE
Keyframe doesn't Work on Alpha in Preview Window Without Adding Transform Strip

### ISSUE THREAD

**Issue by eplipswich** [doakey3/VSE_Transform_Tools#4]
I understand that you can change alpha straight away on a movie strip in the Preview Window without needing to add a Transform Strip. However, attempting to keyframe Alpha by pressing I on the Preview Window doesn't work without the Transform Strip. I presume it doesn't work because all the options in the Insert Keyframe Menu on the Preview Window only work on a Transform Strip. But since you are able to change alpha straight away on a movie strip in the Preview Window without adding a Transform Strip, it would be good if I can also keyframe on the alpha in the Preview Window without adding a Transform Strip.

**Comment by doakey3** [comment]
Fixed with update [#92](https://github.com/doakey3/VSE_Transform_Tools/commit/e6b0987a52ac3e48e1e9ffe9d6fea6b8ba486b41). I've also hidden the keyframing menu options when a transform strip is not selected.
