### ISSUE TITLE
Auto-update does not seem to work

### ISSUE THREAD

**Issue by eplipswich** [doakey3/VSE_Transform_Tools#5]
When I tried to use the auto-updater for the add-on, it somehow doesn't work. It says something like "Redo Unsupported" and "Restart Blender to complete update", but when I restart, it still shows the same old version. I never had this problem before.

This problem started since 1.1.6.

**Comment by doakey3** [comment]
Looks like I didn't update the version number in the __init__.py for 1.1.7 and 1.1.8 until *after* I had uploaded the release. I have removed these two versions. Updating to version 1.1.9 seemed to work fine for me and showed the correct version number after the update.
