### ISSUE TITLE
Add-on not installing

### ISSUE THREAD

**Issue by drpeppercan** [doakey3/VSE_Transform_Tools#7]
Hi there. Happy New Year.
I am using Blender 2.80 in Linux Mint 19.
After installing the ZIP file, and when I click here: screenshot 1
![screenshot from 2019-01-01 10-06-13](https://user-images.githubusercontent.com/21351551/50574055-2d7abd80-0dae-11e9-998d-852b56bb6b00.png)

Then I get this: screenshot 2
![screenshot from 2019-01-01 10-03-54](https://user-images.githubusercontent.com/21351551/50574056-31a6db00-0dae-11e9-91d8-8baaf8af783f.png)

Also, when you click on Report a Bug it brings you here: http://openurl%28https//github.com/doakey3/VSE_Transform_Tools/issues)

**Comment by doakey3** [comment]
Please download the latest Blender 2.8 and try again.

**Comment by drpeppercan** [comment]
Now's working! Thank you doakey3 :)
However, the moment I applied a Transform modifier, the video colors got affected. I have a Color Balance and a Hue Correct Strip Linear Modifiers on this video too.

I am using your tools to rotate the video -90 degrees. But it's only doing it for one frame. Could I rotate the whole video? (it was originally shot with a cellphone in Portrait format).

Thanks in advance doakey3 :)

**Comment by doakey3** [comment]
>  the moment I applied a Transform modifier, the video colors got affected.

Blender's VSE seems to be broken right now (I can't manually add any effect strips), so I assume the dev team is doing some work on it right now. I don't think the color issue is due to a problem with the add-on. However, I noticed that it doesn't occur if you enable "Image Offset" prior to applying a transform modifier.

![demo](https://i.imgur.com/KQIDogW.gif)

> I am using your tools to rotate the video -90 degrees. But it's only doing it for one frame.

Sounds like you have a keyframe somewhere else, so when you go to a different frame, it adjusts to whatever orientation you made on the keyframe.

I noticed that some API changes have introduced some bugs and I just fixed those. I recommend downloading the 1.2.7 release I just made.

**Comment by drpeppercan** [comment]
> "I am using your tools to rotate the video -90 degrees. But it's only doing it for one frame. Could I rotate the whole video? (it was originally shot with a cellphone in Portrait format)."
Never mind about the one above. It's rotating the whole video now :)

But it is still affecting the color adjustments I have with a couple of strip modifiers.

**Comment by drpeppercan** [comment]
> > the moment I applied a Transform modifier, the video colors got affected.
> 
> Blender's VSE seems to be broken right now (I can't manually add any effect strips), so I assume the dev team is doing some work on it right now. I don't think the color issue is due to a problem with the add-on. However, I noticed that it doesn't occur if you enable "Image Offset" prior to applying a transform modifier.
> 
> ![demo](https://camo.githubusercontent.com/7999eccd8a77cf40fd056be6109dbdfb2a9c9b20/68747470733a2f2f692e696d6775722e636f6d2f4b5149446f67572e676966)
> 
> > I am using your tools to rotate the video -90 degrees. But it's only doing it for one frame.
> 
> Sounds like you have a keyframe somewhere else, so when you go to a different frame, it adjusts to whatever orientation you made on the keyframe.
> 
> I noticed that some API changes have introduced some bugs and I just fixed those. I recommend downloading the 1.2.7 release I just made.

Oh, Ok, I just saw your reply! Thanks a bunch for your help doakey3 :)

**Comment by doakey3** [comment]
Whatever was happening yesterday seems to be fixed in today's build.

**Comment by drpeppercan** [comment]
> Whatever was happening yesterday seems to be fixed in today's build.

That's nice! Thanks for the heads up :)

**Comment by drpeppercan** [comment]
Hey doakey3, what are the controls I need to adjust the format/dimensions of the video canvas (most likely it's called something else). After rotating the video from landscape to portrait, a good chunk of the top and the bottom are cropped off.
Thanks

**Comment by drpeppercan** [comment]
> [Autocrop](https://github.com/doakey3/VSE_Transform_Tools#Autocrop) = Shift + C

YES!!!!
Thank you ever so much doakey3!
You made my day!
