### ISSUE TITLE
VSE transform as an official Blender add-on

### ISSUE THREAD

**Issue by NathanLovato** [doakey3/VSE_Transform_Tools#8]
Hi Daniel,

I've gotten in touch with the people working around the Blender VSE, and Richard, the maintainer. There's interest in having a few add-ons distributed as official ones, including the VSE Transform one. Would you be interested in having it distributed there? Do you still have time to maintain it?

If you need a hand with anything, please tell me.

**Comment by Draise14** [comment]
This add-on included by default would be so killer.

**Comment by doakey3** [comment]
I plan to keep this add-on working for the time being... At least until the VSE gets an overhaul (if that happens). I was going to take another close look at all of my add-ons when the official 2.8 got released. I'm pretty busy with work. If I need hand I'll let you know, thanks. If the VSE maintainers would like to make it an add-on that's included by default in Blender, that would be fine with me. I'd be willing to make some tweaks to the code if they see some things that need to be changed first.

**Comment by NathanLovato** [comment]
Good to know you're still on it! For the add-on to get merged in Blender, the add-on's creator/maintainer has to submit it. That's why I was asking.
